"""changes in image field

Revision ID: 177f528c45b9
Revises: ae69652e4619
Create Date: 2025-04-03 16:40:59.140870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177f528c45b9'
down_revision = 'ae69652e4619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.BLOB(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
